[project]
name = "op-down"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "bs4>=0.0.2",
    "img2pdf>=0.6.1",
    "requests>=2.32.5",
]
